services:
  api:
    container_name: node-api
    image: bommxun/node-app:latest
    env_file:
      - env
    ports:
      - 5000:5000
    networks:
      - node-network
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=/dashboard-p/'
    ports:
      - 9090:9090
    networks:
      - node-network
    restart: always
  
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - node-network
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/dashboard-g/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - node-network
    restart: always

volumes:
  grafana-data:
  prometheus-data:

networks:
  node-network:
    driver: bridge